spring.application.name=Auth
server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/auf
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret
app.jwt-secret=TSiPOdEBdgMbs6HkBUpB4hpUUZV58PuyqjIhOyTlXHQ=
app.jwt-expiration-ms=86400000 # 24 ????

# Google OAuth 2.0
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/login/oauth2/code/google



logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG